### ISSUE TITLE
Demo URL not working

### ISSUE THREAD

**Issue by chaitu0788** [yanaiela/num_fh#2]
Hi,

When I try demo URL with an input text, it is showing "Service Unavailable"

http://nlp.biu.ac.il/~lazary/fh/

**Comment by yanaiela** [comment]
Hey,

Sorry about that. It is now up again.

On a side note, you can host the demo locally:
```
cd /'path-to-parent-dir'/num_fh/
export FLASK_APP=num_fh/demo/server.py
flask run --port 5000 --host "" # or whatever port / host
```
